pom.xml

- Updates version to 3.0.2
- corrects whitespace for release profile in pom.xml

Bumps version to 3.0.2

---

src/main/java/com/capitalone/dashboard/client/RestClient.java

Added log statement to monitor the timings on the rest calls

Added log statement to monitor the timings on the rest calls

---

pom.xml
src/main/java/com/capitalone/dashboard/model/SCM.java

Added fields to capture files (added, removed and modified) for a commit.

Included change to capture file names

---

pom.xml
src/main/java/com/capitalone/dashboard/model/CollectorType.java
src/main/java/com/capitalone/dashboard/model/TestResult.java
src/main/java/com/capitalone/dashboard/model/TestSuiteType.java
src/main/java/com/capitalone/dashboard/repository/CollectorItemRepository.java
src/main/java/com/capitalone/dashboard/repository/FeatureRepository.java
src/main/java/com/capitalone/dashboard/util/FeatureCollectorConstants.java

Core module changes required for Jira XRay Test Results Collector

Jira xray core changes

---

pom.xml

updating core version to 3.0.7-SNAPSHOT

updating core version to 3.0.7-SNAPSHOT

---

src/main/java/com/capitalone/dashboard/model/ServiceAccount.java

SystemId Whitelist - Allowed service accounts - service_accounts

SystemId Whitelist - Allowed service accounts - service_accounts

---

pom.xml
travis-utilities/release.sh

- implemented semantic versioning on the pom.xml
- added maven release:prepare and release:perform task to the release script.

Fix the release process for Hygieia Core project

---

src/main/java/com/capitalone/dashboard/util/FeatureCollectorConstants.java

Added Feature Collector Constants to be used by Jira Collector

Added Feature Collector Constants to be used by Jira Collector

---

src/main/java/com/capitalone/dashboard/event/sync/SyncDashboard.java
src/main/java/com/capitalone/dashboard/model/CodeReposBuilds.java
src/main/java/com/capitalone/dashboard/model/RepoBranch.java
src/main/java/com/capitalone/dashboard/repository/BuildRepository.java
src/main/java/com/capitalone/dashboard/repository/CodeReposBuildsRepository.java

-  Added findTop1ByCollectorItemIdAndBuildStatusOrderByTimestampDesc to Build Repository.
-  Created a new Model and Repository class to support collection: code_repos_builds.
-  Fixed the sync dashboard (addCollectorItemToDashboard) for Build collector item, associate build to dashboard only if the codeRepos built is a proper subset of repoURL and branch configuration in SCM collector items associated with the component.

Sync Dashboard Changes

---

src/main/java/com/capitalone/dashboard/model/Incident.java
src/main/java/com/capitalone/dashboard/repository/CmdbRepository.java
src/main/java/com/capitalone/dashboard/repository/DashboardRepository.java

Adding model,repository updates to support incident reporting

Adding model,repository updates to support incident reporting

---

src/main/java/com/capitalone/dashboard/repository/CommitRepository.java

updated the method to order by timestamp and return a list

updated the method to order by timestamp and return a list

---

src/main/java/com/capitalone/dashboard/event/sync/SyncDashboard.java
src/main/java/com/capitalone/dashboard/model/RepoBranch.java
src/main/java/com/capitalone/dashboard/repository/CodeQualityRepository.java
src/test/java/com/capitalone/dashboard/event/sync/SyncDashboardTest.java

1. Fixed issues with SyncDashboard.sync with Code Quality relational item.
2. normalized branch for Git in RepoBranch.

SyncDashboard Bug fix and Normalize branch for Git

---

src/main/java/com/capitalone/dashboard/event/TestResultEventListener.java
src/main/java/com/capitalone/dashboard/model/CollectorItem.java
src/main/java/com/capitalone/dashboard/model/TestCase.java
src/test/java/com/capitalone/dashboard/event/TestResultEventListenerTest.java

This PR adds TestResultEventListener which creates new performance collection documents for every test_result collection's performance documents posted through external performance tools

Added TestResultEventListener

---

src/main/java/com/capitalone/dashboard/model/AuditResult.java

This PR is created to have the traceability details in audit results collection data for test_result audit type

Traceability details in audit results data

---

src/main/java/com/capitalone/dashboard/model/LibraryPolicyResult.java

Added buildId to the model to support association with build if present.

add buildId to the model

---

src/main/java/com/capitalone/dashboard/event/TestResultEventListener.java

This PR is created for performance collection gets updated with actualErrorRate data

performance collection updated with actual error rate

---

src/main/java/com/capitalone/dashboard/model/AuditResult.java

AuditResult Data model added with options

auditresult data model updated

---

pom.xml
src/main/java/com/capitalone/dashboard/collector/CollectorTaskWithGenericItem.java
src/test/java/com/capitalone/dashboard/collector/CollectorTaskWithGenericItemTest.java
src/test/java/com/capitalone/dashboard/collector/TestCollectorTaskTwoWithGenericItem.java
src/test/java/com/capitalone/dashboard/collector/TestCollectorTaskWithGenericItem.java

Collectors that need to process generic items created by jenkins plugin, can extend this new Abstract class that has the the method to process generic item for a given collector.

Added CollectorTaskWithGenericItem extending CollectorTask.

---

src/main/java/com/capitalone/dashboard/model/AuditResult.java

Reverts Hygieia/hygieia-core#54

Revert "auditresult data model updated"

---

src/main/java/com/capitalone/dashboard/model/BinaryArtifact.java

modified timestamp datatype to long

modified timestamp datatype to long

---

src/main/java/com/capitalone/dashboard/model/AuditResult.java

This PR is created to add options field in audit result model, and added new collector.

audit result model added with options

---

src/main/java/com/capitalone/dashboard/model/quality/CheckstyleReport.java
src/main/java/com/capitalone/dashboard/model/quality/CodeQualityVisitee.java
src/main/java/com/capitalone/dashboard/model/quality/CodeQualityVisitor.java
src/main/java/com/capitalone/dashboard/model/quality/CucumberJsonReport.java
src/main/java/com/capitalone/dashboard/model/quality/FindBugsXmlReport.java
src/main/java/com/capitalone/dashboard/model/quality/JacocoXmlReport.java
src/main/java/com/capitalone/dashboard/model/quality/JunitXmlReport.java
src/main/java/com/capitalone/dashboard/model/quality/MochaJsSpecReport.java
src/main/java/com/capitalone/dashboard/model/quality/PmdReport.java
src/main/java/com/capitalone/dashboard/model/quality/QualityVisitee.java
src/main/java/com/capitalone/dashboard/model/quality/QualityVisitor.java

Note this is for a PR in the Hygieia project - setup support for mocha js spec file results for publisher plugin

Feature results format

---

src/main/java/com/capitalone/dashboard/model/BinaryArtifact.java

Artifact Audit changes- Binary artifact buildInfo

Artifact Audit changes- Binary artifact buildInfo 

---

src/main/java/com/capitalone/dashboard/model/BinaryArtifact.java
src/main/java/com/capitalone/dashboard/model/LibraryPolicyResult.java
src/test/java/com/capitalone/dashboard/model/LibraryPolicyResultTest.java

OSS enhancement

---

src/main/java/com/capitalone/dashboard/request/GenericCollectorItemCreateRequest.java

Generic collectorItem - artifactory - capture pattern

Generic collectorItem - artifactory - capture pattern

---

src/main/java/com/capitalone/dashboard/request/GenericCollectorItemCreateRequest.java

GenericCollectorItem - pattern

GenericCollectorItem - pattern

---

src/main/java/com/capitalone/dashboard/model/BuildStage.java
src/main/java/com/capitalone/dashboard/model/adapter/BuildStageAdapter.java

- BuildStage now extends BaseModel
- Added BuildStageAdapter to support GsonDeserialization.

Change BuildStage to extend off BaseModel

---

src/main/java/com/capitalone/dashboard/model/BuildStage.java
src/main/java/com/capitalone/dashboard/model/Error.java
src/main/java/com/capitalone/dashboard/model/adapter/BuildStageAdapter.java
src/main/java/com/capitalone/dashboard/request/GenericCollectorItemCreateRequest.java

Hygieia Plugin - Publish stages- parse error

Hygieia Plugin - Publish stages- parse error

---

src/main/java/com/capitalone/dashboard/config/MongoConfig.java

"dashboard" should be "dashboarddb" as referenced in other examples and default configs

Normalize defaults

---

pom.xml

- removed -Xdoclint:none and replaced it with doclint

Resolve Build issues with Travis CI

---

src/main/resources/logback.xml

Add thread name to logs

---

src/main/java/com/capitalone/dashboard/model/score/settings/ScmScoreSettings.java

fix #93 
this is for Hygieia/Hygieia#3011 where you can see exactly what the problem is.

fix scm score category name

---

src/main/java/com/capitalone/dashboard/event/sync/SyncDashboard.java
src/main/java/com/capitalone/dashboard/model/FeatureFlag.java
src/main/java/com/capitalone/dashboard/model/adapter/FeatureFlagAdapter.java
src/main/java/com/capitalone/dashboard/repository/FeatureFlagRepository.java
src/test/java/com/capitalone/dashboard/event/sync/SyncDashboardTest.java

Feature flags to toggle auto-discovery feature enabled by Hygieia publisher plugin.

Feature flags - toggle auto-discovery feature

---

src/main/java/com/capitalone/dashboard/repository/BinaryArtifactRepository.java

findByArtifactNameAndArtifactVersion

findByArtifactNameAndArtifactVersion

---

src/main/java/com/capitalone/dashboard/model/BinaryArtifact.java
src/main/java/com/capitalone/dashboard/repository/BinaryArtifactRepository.java

Binaryartifact override equals and hash

Binaryartifact override equals and hash

---

src/main/java/com/capitalone/dashboard/model/AutoDiscoverCollectorItem.java
src/main/java/com/capitalone/dashboard/model/AutoDiscoveredEntry.java
src/main/java/com/capitalone/dashboard/model/AutoDiscovery.java
src/main/java/com/capitalone/dashboard/model/AutoDiscoveryMetaData.java
src/main/java/com/capitalone/dashboard/model/AutoDiscoveryRemoteRequest.java
src/main/java/com/capitalone/dashboard/model/AutoDiscoveryStatusType.java
src/main/java/com/capitalone/dashboard/model/AutoDiscoverySubscriberRemoteRequest.java
src/main/java/com/capitalone/dashboard/model/CollectorType.java
src/main/java/com/capitalone/dashboard/repository/ComponentRepository.java
src/main/java/com/capitalone/dashboard/repository/RelatedCollectorItemRepository.java

Related Items collector model changes

Related Items collector model changes

---

src/main/java/com/capitalone/dashboard/repository/CustomRepositoryQuery.java
src/main/java/com/capitalone/dashboard/repository/CustomRepositoryQueryImpl.java

get all metadata with searchIdentifier

get all metadata with searchIdentifier

---

src/main/java/com/capitalone/dashboard/event/sync/SyncDashboard.java
src/main/java/com/capitalone/dashboard/repository/BaseCollectorItemRepository.java
src/main/java/com/capitalone/dashboard/util/FeatureFlagsEnum.java
src/main/java/com/capitalone/dashboard/util/HygieiaUtils.java

- Fix for feature flag functionality for toggle between automated sync and manual sync by relateditems collector.
- Added Enum for Featureflags
- When creating the related item record for build and SCM repo added additional filter to include branch if available.

Bug Fixes for feature flag toggle

---

src/main/java/com/capitalone/dashboard/model/PullRequestEvent.java

PullRequestEvent - List of all pull request events via Github webhook.

PullRequestEvent 

---

src/main/java/com/capitalone/dashboard/repository/SonarProjectRepository.java

This is PR is new method to find sonar project is added

New method to find sonar project added

---

src/main/java/hygieia/transformer/CucumberJsonToTestCapabilityTransformer.java
src/main/java/hygieia/transformer/HygieiaConstants.java
src/main/java/hygieia/transformer/MochaSpecToTestCapabilityTransformer.java
src/main/java/hygieia/transformer/QualityVisiteeDeserializer.java
src/main/java/hygieia/transformer/TestResultVisitor.java
src/main/java/hygieia/transformer/Transformer.java
src/test/java/hygieia/transformer/CodeQualityVisiteeDeserializerTest.java
src/test/java/hygieia/transformer/CucumberJsonToTestResultTransformerTest.java
src/test/java/hygieia/transformer/MochaSpecToTestCapabilityTransformerTest.java
src/test/java/hygieia/transformer/TestResultVisitorTest.java
src/test/resources/checkstyle-report.xml
src/test/resources/cucumber.json
src/test/resources/findbugs.xml
src/test/resources/jacoco.xml
src/test/resources/junit.xml
src/test/resources/mochjsspec.json
src/test/resources/pmd.xml

- Added Transformer for Cucumber Json
- Added Transformer for Mocha Spec

Add TestResult transformers

---

src/main/java/com/capitalone/dashboard/model/CollectionMode.java
src/main/java/com/capitalone/dashboard/model/GitHubPaging.java
src/main/java/com/capitalone/dashboard/repository/GitHubRepoRepository.java
src/main/java/com/capitalone/dashboard/util/CommitPullMatcher.java
src/main/java/com/capitalone/dashboard/util/GithubGraphQLQuery.java

Github utils

---

pom.xml
src/main/java/com/capitalone/dashboard/model/quality/JunitXmlReport.java
src/main/java/hygieia/transformer/CucumberJsonToTestCapabilityTransformer.java
src/main/java/hygieia/transformer/JunitXmlToTestCapabilityTransformer.java
src/test/java/hygieia/transformer/CucumberJsonToTestResultTransformerTest.java
src/test/java/hygieia/transformer/JunitXmlToTestCapabilityTransformerTest.java

Added Transformer for Junit

---

src/main/java/com/capitalone/dashboard/repository/BaseCollectorItemRepository.java
src/main/java/com/capitalone/dashboard/repository/BinaryArtifactRepository.java
src/main/java/com/capitalone/dashboard/repository/CollectorItemRepository.java
src/main/java/com/capitalone/dashboard/repository/GitRequestRepository.java
src/main/java/com/capitalone/dashboard/repository/LibraryPolicyResultsRepository.java

getTopInstanceRecord sorted by timestamp desc

getTopInstanceRecord sorted by timestamp desc

---

src/main/java/com/capitalone/dashboard/repository/MaturityModelRepository.java

This PR is created to update the correct return type of repository function.

MaturityModelRepository function return type update

---

src/main/java/com/capitalone/dashboard/event/sync/SyncDashboard.java
src/main/java/com/capitalone/dashboard/repository/RelatedCollectorItemRepository.java

Enable scm collectorItems for auto discovery

---

pom.xml

Increment Version 3.6.3-SNAPSHOT

---

pom.xml

added profileid to avoid duplicate staging directories

---

pom.xml

automate releases to maven central

---

pom.xml

Increment Version to 3.6.4-SNAPSHOT

---

pom.xml

Increment version to 3.6.6-SNAPSHOT

---

src/main/java/com/capitalone/dashboard/config/MongoConfig.java

Add connection and socket timeouts for MongoDB connections

Add timeouts for database accesses

---

pom.xml
src/main/java/com/capitalone/dashboard/config/MongoConfig.java

Update version to 3.6.7-SNAPSHOT

Update version to 3.6.7-SNAPSHOT

---

pom.xml
src/main/java/com/capitalone/dashboard/config/MongoConfig.java

Update version to 3.6.8-SNAPSHOT

Update version to 3.6.8-SNAPSHOT

---

pom.xml

updated version to 3.6.9-SNAPSHOT
---

updated version to 3.6.9-SNAPSHOT

---

pom.xml

- Fix SAST Vulnerabilities around transitive dependencies xstream-1.4.7.jar and plexus-utils-3.0.8.jar
- Fix licensing vulnerability around xmlpull-1.1.3.1.jar
- Temporarily disable automatic publish to Maven Central

Fix SAST Vulnerabilities for hygieia-core

---

pom.xml

re-enable Auto Publish to Maven

---

pom.xml

Fix Vulnerabilities around jackson-version

---

pom.xml

Increment Version to 3.7.0-SNAPSHOT

---

pom.xml

Fix SCA Scan vulnerabilities affecting the below libraries
- commons-codec
- commons-lang3
- commons-collection

fix SCA scan vulnerabilities for hygieia-core

---

pom.xml
src/main/java/com/capitalone/dashboard/model/CodeQualityMetric.java
src/main/java/com/capitalone/dashboard/model/Instance.java

Add instance to CodeQualityMetric

---

pom.xml

Upgraded spring-security-core :4.2.13

---

pom.xml

upgraded spring-security-core :4.2.17

---

pom.xml
src/main/java/com/capitalone/dashboard/model/Comment.java
src/main/java/com/capitalone/dashboard/model/GitRequest.java
src/main/java/com/capitalone/dashboard/model/Review.java
src/main/java/com/capitalone/dashboard/model/SCM.java

Change authorType from enum to string

---

pom.xml
src/main/java/com/capitalone/dashboard/model/BinaryArtifact.java
src/main/java/com/capitalone/dashboard/repository/BinaryArtifactRepository.java

update BinaryArtifact item and add repository method

---

pom.xml
src/main/java/com/capitalone/dashboard/model/BinaryArtifact.java
src/main/java/com/capitalone/dashboard/repository/BinaryArtifactRepository.java

bump core version and add binary artifact query method

---

pom.xml

Fix security vulnerability for tomcat-embed-core

Bump tomcat-embed-core from 8.5.32 to 8.5.55

---

pom.xml
src/main/java/com/capitalone/dashboard/repository/BinaryArtifactRepository.java

add additional query method to Binary Artifact Repo

---

pom.xml
src/main/java/com/capitalone/dashboard/model/CollectorType.java

Added Api to collectorType in core.

add api to collectorType

---

pom.xml
src/main/java/com/capitalone/dashboard/model/LibraryPolicyResult.java
src/main/java/com/capitalone/dashboard/model/WhiteSourceProduct.java
src/main/java/com/capitalone/dashboard/model/WhiteSourceProject.java

core changes for whitesource collector - Incremented to 3.7.19

---

pom.xml
src/main/java/com/capitalone/dashboard/model/WhiteSourceChangeRequest.java

Whitesource collector- ChangeRequest

---

pom.xml
src/main/java/com/capitalone/dashboard/client/DefaultRestClientSettings.java
src/main/java/com/capitalone/dashboard/client/RestClient.java
src/main/java/com/capitalone/dashboard/testutil/BaseCollectorTestConfig.java

- Provided default bean implementation for RestClientSettings
- Added missing httpclient and httpcore libraries to make the Rest operations work

Changes for RestClient to make it work

---

pom.xml
src/main/java/com/capitalone/dashboard/collector/CollectorTask.java

- Restored the capability to limit the collection of data by search criteria

Restore the multiple search criteria for collectors

---

pom.xml
src/main/java/com/capitalone/dashboard/model/LibraryPolicyReference.java
src/main/java/com/capitalone/dashboard/model/WhiteSourceChangeRequest.java
src/main/java/com/capitalone/dashboard/model/WhiteSourceComponent.java
src/main/java/com/capitalone/dashboard/repository/LibraryReferenceRepository.java

Whitesource collector - model changes

---

pom.xml
src/main/java/com/capitalone/dashboard/model/Cmdb.java

PR is to update cmdb model with additional fields

cmdb model update

---

pom.xml
src/main/java/com/capitalone/dashboard/model/Cmdb.java

CMDB - added commonName to hashCode

---

pom.xml
src/main/java/com/capitalone/dashboard/repository/CmdbRepository.java

PR to cmdb search method by CInumber/legacyName/commonName/CIkey

cmdb configuration Item search

---

pom.xml
src/main/java/com/capitalone/dashboard/model/Cmdb.java

cmdb model indexes added

---

pom.xml
src/main/java/com/capitalone/dashboard/model/AuditRequestLog.java

- Add `clientReference` field to `audit_requests` collection for maintainability.

add clientReference field for Audit Request Logging

---

pom.xml
src/main/java/com/capitalone/dashboard/model/LibraryPolicyResult.java

Librarypolicy result - add policy name

---

pom.xml
src/main/java/com/capitalone/dashboard/model/EnvironmentComponent.java
src/main/java/com/capitalone/dashboard/request/DeployDataCreateRequest.java

- Added metadata to capture more artifact information for deploys

Enhance deploy scripts

---

pom.xml

Added javax.xml.bind to fix build issues.

pom dependency addition

---

pom.xml
src/main/java/com/capitalone/dashboard/model/WhiteSourceComponent.java

Changed WS unique fields to orgName and project token

---

pom.xml
src/main/java/com/capitalone/dashboard/model/Build.java
src/main/java/com/capitalone/dashboard/request/DeployDataCreateRequest.java

- Added deployMetadata to Build.
- Added buildUrl to DeployDataCreateRequest.

Added more fields to Build and Deploy Request

---

pom.xml
src/main/java/com/capitalone/dashboard/model/WhiteSourceChangeRequest.java

Changed WS scopeId to Long

---

pom.xml
src/main/java/com/capitalone/dashboard/repository/LibraryPolicyResultsRepository.java

LibraryPolicy - evaluationTimestamp desc

---

pom.xml
src/main/java/com/capitalone/dashboard/model/quality/JunitXmlReportV2.java
src/main/java/com/capitalone/dashboard/model/quality/QualityVisitor.java
src/main/java/hygieia/transformer/JunitXmlToTestCapabilityTransformerV2.java
src/main/java/hygieia/transformer/TestResultVisitor.java

added additional test result xml format

---

pom.xml
src/main/java/com/capitalone/dashboard/repository/BuildRepository.java
src/main/java/com/capitalone/dashboard/repository/CollectorItemRepository.java

add additional query for build and collector item repo

---

pom.xml
src/main/java/com/capitalone/dashboard/model/GitHubCollector.java
src/main/java/com/capitalone/dashboard/model/webhook/github/GitHubRepo.java

Add github related models

---

pom.xml
src/main/java/com/capitalone/dashboard/model/BaseModel.java
src/main/java/com/capitalone/dashboard/model/Collector.java
src/main/java/com/capitalone/dashboard/model/CollectorItemMetadata.java
src/main/java/com/capitalone/dashboard/model/LibraryPolicyReference.java
src/main/java/com/capitalone/dashboard/repository/CollectorItemMetadataRepository.java

1. Added upsertTime to BaseModel.
2. Added Human readable lastExecutedTime to Collector Model.
3. Added lastExceutedSecondsfield to Collector Model.
4. Added searchable methods to CollectorItemMetadataRepository.
5. added language support to library_reference Model.

More Enhancements to collector_item_metadata

---

pom.xml
src/main/java/com/capitalone/dashboard/model/GitRequest.java
src/main/java/com/capitalone/dashboard/util/GithubGraphQLQuery.java

Update GitRequest model

---

pom.xml
src/main/java/com/capitalone/dashboard/model/AutoDiscoverAuditType.java

Autodiscovery type

---

pom.xml
src/main/java/com/capitalone/dashboard/model/RequestLog.java
src/main/java/com/capitalone/dashboard/util/CommonConstants.java

RequestLog - added source for logging 

---

README.md
pom.xml
src/main/java/com/capitalone/dashboard/model/AuthType.java

sso auth type added

---

pom.xml
src/main/java/com/capitalone/dashboard/model/CollectorType.java

CollectoryType - InfraScan

---

pom.xml
src/main/java/com/capitalone/dashboard/repository/BaseCollectorRepository.java
src/main/java/com/capitalone/dashboard/service/CollectorService.java
src/main/java/com/capitalone/dashboard/service/CollectorServiceImpl.java

- BaseCollectorRepository now extends PagingAndSortingRepository (which extends CrudRepository)
- New collector service function all() to return all collectors sorted alphabetically
- pom version bump

Collector Service to get all

---

pom.xml
src/main/java/com/capitalone/dashboard/event/sync/SyncDashboard.java
src/test/java/com/capitalone/dashboard/event/sync/SyncDashboardTest.java

Syncd dashboard - build and codequality

---

pom.xml
src/main/java/com/capitalone/dashboard/model/CodeQuality.java

CodeQuality - severity counts

---

pom.xml
src/main/java/com/capitalone/dashboard/model/CodeQuality.java
src/main/java/com/capitalone/dashboard/repository/InfrastructureScanRepository.java

InfrastructureScanRepository - added delete()

---

pom.xml
src/main/java/com/capitalone/dashboard/model/Vulnerability.java

Add isRemediationRequired and isRiskAccepted fields to vulnerability model

Add fields to vuln

---

pom.xml
src/main/java/com/capitalone/dashboard/model/AuditReport.java

Auditreport sourceIdentifier

---

pom.xml
src/main/java/com/capitalone/dashboard/repository/InfrastructureScanRepository.java

Add method to infraScan repo: findByCollectorItemIdOrderByTimestampDesc

Update version, add method to InfraScan repo

---

pom.xml
src/main/java/com/capitalone/dashboard/model/AuditType.java
src/main/java/com/capitalone/dashboard/model/ContainerScan.java
src/main/java/com/capitalone/dashboard/repository/AuditReportRepository.java
src/main/java/com/capitalone/dashboard/repository/ContainerScanRepository.java

Container_Scan Audit Type

---

pom.xml
src/main/java/com/capitalone/dashboard/model/EnvironmentComponent.java

Environment component -scmRepo/identifier

---

pom.xml
src/main/java/com/capitalone/dashboard/repository/AuditReportRepository.java

Added method to get new audit reports of a certain type to be used in testresult-sync collector

Add method for testresult-sync to auditReportRepository

---

pom.xml
src/main/java/com/capitalone/dashboard/config/MongoConfig.java

sslInvalidHostNameAllowed mongo option added to handle cert changes

sslInvalidHostNameAllowed mongo option added

---

pom.xml
src/main/java/com/capitalone/dashboard/model/AuditReport.java
src/main/java/com/capitalone/dashboard/model/EvaluationStatus.java
src/main/java/com/capitalone/dashboard/repository/AuditReportRepository.java
src/test/java/com/capitalone/dashboard/repository/AuditReportRepositoryTest.java
src/test/java/com/capitalone/dashboard/util/LoadTestData.java
src/test/resources/audit_reports/audit_reports.json

AuditReport - search by auditType and auditresponse

---

pom.xml
src/main/java/com/capitalone/dashboard/model/AuditType.java
src/main/java/com/capitalone/dashboard/model/TestResult.java

Update test result model for new feature test flow
Add audit type for same initiative

Update test result model and add new audit type

---

pom.xml
src/main/java/com/capitalone/dashboard/model/AutoDiscoveryMetaData.java

AutoDiscoveryMetaData added properties

---

pom.xml
src/main/java/com/capitalone/dashboard/model/AuditReport.java

Refresh attributes

---

pom.xml
src/main/java/com/capitalone/dashboard/model/AuditReport.java
src/main/java/com/capitalone/dashboard/model/ContainerScan.java
src/main/java/com/capitalone/dashboard/repository/ContainerScanRepository.java

ContainerScan - Image attributes 

---

pom.xml
src/main/java/hygieia/transformer/JunitXmlToTestCapabilityTransformer.java
src/main/java/hygieia/transformer/JunitXmlToTestCapabilityTransformerV2.java

Update Junittransformer - successCount
